# Reference this view as products
schema: fashionly

dimensions:
  brand: {}
  category: {}
  cost: {}
  department: {}
  name: {}
  sku: {}

  distribution_center_id:
    format: ID

  id:
    format: ID
    primary_key: true

measures:
  count:
    aggregate_type: count
